from pathlib import Path
import json
import os
import sys
from uuid import uuid4

from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
os.environ["CREATE_VALIDATE_LLM_CONFIG"] = "false"
os.environ["CREATE_STATIC_GENERATION"] = "false"

from app.config import get_settings
from app.agents.graphs.llm_adapter import LLMGraphResult, build_llm_call_metrics
from app.main import app
from app.services import create_service


class FakeLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        payload_text = json.dumps(payload, ensure_ascii=False)
        if "Yahaha Cover Agent" in payload_text:
            output = {
                "svg": "<svg xmlns='http://www.w3.org/2000/svg' width='1200' height='900'><rect width='1200' height='900' fill='#101827'/><text x='80' y='180' fill='#ffffff' font-size='88'>LLM Arcade</text></svg>",
                "mimeType": "image/svg+xml",
                "summary": "A generated SVG catalog cover for LLM Arcade.",
            }
            text = json.dumps(output, ensure_ascii=False)
            raw = {"output_text": text, "usage": {"input_tokens": 8, "output_tokens": 13, "total_tokens": 21}}
            return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))
        output = {
            "type": "final",
            "output": {
                "Finished": True,
                "files": [
                    {
                        "path": "index.html",
                        "content": """<!doctype html><html><body><canvas id='game'></canvas><script>window.parent.postMessage({source:'yahaha-game',type:'game_ready',gameId:'x'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
                    },
                    {"path": "manifest.json", "content": "{}"},
                    {"path": "source.json", "content": "{\"generator\":\"fake-llm\"}"},
                ],
                "cover": {"title": "LLM Arcade", "description": "Generated by fake LLM.", "tags": ["llm"]},
                "implementationSummary": "A minimal iframe-safe game document.",
                "safetyNotes": ["No privileged APIs."],
            },
        }
        text = json.dumps(output, ensure_ascii=False)
        raw = {"output_text": text, "usage": {"input_tokens": 12, "output_tokens": 34, "total_tokens": 46}}
        return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))


class BadLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        raw = {"output_text": "not json", "usage": {"output_tokens": 2}}
        return LLMGraphResult(text="not json", raw=raw, metrics=build_llm_call_metrics(payload, response_text="not json", response_raw=raw))


class BadCoverLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        payload_text = json.dumps(payload, ensure_ascii=False)
        if "Yahaha Cover Agent" in payload_text:
            raw = {"output_text": "{\"summary\":\"no image\"}", "usage": {"output_tokens": 3}}
            return LLMGraphResult(text=raw["output_text"], raw=raw, metrics=build_llm_call_metrics(payload, response_text=raw["output_text"], response_raw=raw))
        return FakeLLMAdapter().invoke(payload)


def run() -> None:
    get_settings.cache_clear()
    assert get_settings().create_static_generation is False
    create_service._make_graph_adapter = lambda ai_config: FakeLLMAdapter()  # type: ignore[assignment]

    client = TestClient(app)
    email = f"llm-{uuid4().hex[:10]}@yahaha.local"
    auth_register = client.post(
        "/auth/register",
        json={"email": email, "password": "password123", "displayName": "LLM User"},
    )
    assert auth_register.status_code == 200
    token = auth_register.json()["accessToken"]

    ai_config = client.put(
        "/create/ai-config",
        json={"baseUrl": "https://api.example.test/v1", "model": "test-model", "apiKey": "test-api-key"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert ai_config.status_code == 200

    create_job = client.post(
        "/create/jobs",
        json={"prompt": "make an llm arcade game", "files": [], "agentMode": "plan", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert create_job.status_code == 202
    payload = create_job.json()
    assert payload["status"] == "planning"
    final_job = client.get(f"/create/jobs/{payload['id']}", headers={"Authorization": f"Bearer {token}"})
    assert final_job.status_code == 200
    payload = final_job.json()
    assert payload["status"] == "completed"
    assert payload["agentMode"] == "plan"
    assert payload["gameSlug"].startswith("llm-arcade-")

    steps = client.get(f"/create/runs/{payload['runId']}/steps", headers={"Authorization": f"Bearer {token}"})
    assert steps.status_code == 200
    step_payload = steps.json()
    stages = [step["stage"] for step in step_payload]
    assert "llm_call" in stages
    assert "cover_prompt_rendered" in stages
    assert "cover_llm_call" in stages
    assert "cover_generated" in stages
    assert "cover_uploaded" in stages
    assert "llm_generation_completed" in stages
    llm_step = next(step for step in step_payload if step["stage"] == "llm_call")
    assert llm_step["metrics"]["outputTokens"] == 34
    cover_step = next(step for step in step_payload if step["stage"] == "cover_generated")
    assert cover_step["metrics"]["contentType"] == "image/svg+xml"

    events = client.get(f"/create/runs/{payload['runId']}/events", headers={"Authorization": f"Bearer {token}"})
    assert events.status_code == 200
    assert "event: llm_call" in events.text
    assert "cover_uploaded" in events.text
    assert "event: done" in events.text

    games = client.get("/games")
    assert games.status_code == 200
    created_game = next(game for game in games.json() if game["id"] == payload["gameSlug"])
    assert "/cover.svg" in created_game["coverUrl"]

    manifest = client.get(f"/play/{payload['gameSlug']}/manifest")
    assert manifest.status_code == 200
    assert any("/cover.svg" in asset for asset in manifest.json()["assets"])

    document = client.get(f"/play/{payload['gameSlug']}/document")
    assert document.status_code == 200
    assert "requestAnimationFrame" in document.text

    create_service._make_graph_adapter = lambda ai_config: BadLLMAdapter()  # type: ignore[assignment]
    failed_job = client.post(
        "/create/jobs",
        json={"prompt": "return malformed output", "files": [], "agentMode": "plan", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert failed_job.status_code == 202
    failed_start = failed_job.json()
    failed_final = client.get(f"/create/jobs/{failed_start['id']}", headers={"Authorization": f"Bearer {token}"})
    assert failed_final.status_code == 200
    failed_payload = failed_final.json()
    assert failed_payload["status"] == "failed"
    assert failed_payload["gameSlug"] is None
    failed_events = client.get(f"/create/runs/{failed_payload['runId']}/events", headers={"Authorization": f"Bearer {token}"})
    assert failed_events.status_code == 200
    assert "event: error" in failed_events.text

    create_service._make_graph_adapter = lambda ai_config: BadCoverLLMAdapter()  # type: ignore[assignment]
    failed_cover_job = client.post(
        "/create/jobs",
        json={"prompt": "valid game but invalid cover", "files": [], "agentMode": "plan", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert failed_cover_job.status_code == 202
    failed_cover_start = failed_cover_job.json()
    failed_cover_final = client.get(f"/create/jobs/{failed_cover_start['id']}", headers={"Authorization": f"Bearer {token}"})
    assert failed_cover_final.status_code == 200
    failed_cover_payload = failed_cover_final.json()
    assert failed_cover_payload["status"] == "failed"
    assert failed_cover_payload["gameSlug"] is None
    failed_cover_steps = client.get(f"/create/runs/{failed_cover_payload['runId']}/steps", headers={"Authorization": f"Bearer {token}"})
    assert failed_cover_steps.status_code == 200
    failed_cover_stages = [step["stage"] for step in failed_cover_steps.json()]
    assert "cover_llm_call" in failed_cover_stages
    assert "run_failed" in failed_cover_stages


if __name__ == "__main__":
    run()
    print("create llm generation checks passed")
