from pathlib import Path
import base64
import json
import os
import sys
from uuid import uuid4

from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
os.environ["CREATE_VALIDATE_LLM_CONFIG"] = "false"
os.environ["CREATE_STATIC_GENERATION"] = "false"

from app.config import get_settings
from app.agents.graphs.llm_adapter import LLMGraphResult, build_llm_call_metrics
from app.agents.create import AgentArtifact
from app.agents.framework.workspace import WorkspaceContext, WorkspaceFS
from app.main import app
from app.services import create_service


class FakeLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        payload_text = json.dumps(payload, ensure_ascii=False)
        if "Yahaha Cover Agent" in payload_text:
            output = {
                "svg": "<svg xmlns='http://www.w3.org/2000/svg' width='1200' height='900'><rect width='1200' height='900' fill='#101827'/><text x='80' y='180' fill='#ffffff' font-size='88'>LLM Arcade</text></svg>",
                "mimeType": "image/svg+xml",
                "summary": "A generated SVG catalog cover for LLM Arcade.",
            }
            text = json.dumps(output, ensure_ascii=False)
            raw = {"output_text": text, "usage": {"input_tokens": 8, "output_tokens": 13, "total_tokens": 21}}
            return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))
        if "Yahaha ReAct Create Agent" in payload_text and "toolResults" not in payload_text:
            output = {
                "type": "tool",
                "tool": {
                    "name": "workspace.file_write",
                    "args": {
                        "path": "index.html",
                        "content": """<!doctype html><html><body><canvas id='game'></canvas><script>window.parent.postMessage({source:'yahaha-game',type:'game_ready',gameId:'x'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
                    },
                },
            }
            text = json.dumps(output, ensure_ascii=False)
            raw = {"output_text": text, "usage": {"input_tokens": 12, "output_tokens": 21, "total_tokens": 33}}
            return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))
        file_entry = (
            {"path": "index.html", "workspacePath": "index.html"}
            if "Yahaha ReAct Create Agent" in payload_text
            else {
                "path": "index.html",
                "content": """<!doctype html><html><body><canvas id='game'></canvas><script>window.parent.postMessage({source:'yahaha-game',type:'game_ready',gameId:'x'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
            }
        )
        output = {
            "type": "final",
            "output": {
                "Finished": True,
                "files": [file_entry],
                "cover": {"title": "LLM Arcade", "description": "Generated by fake LLM.", "tags": ["llm"]},
                "implementationSummary": "A minimal iframe-safe game document.",
                "safetyNotes": ["No privileged APIs."],
            },
        }
        text = json.dumps(output, ensure_ascii=False)
        raw = {"output_text": text, "usage": {"input_tokens": 12, "output_tokens": 34, "total_tokens": 46}}
        return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))


class OptReactLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        payload_text = json.dumps(payload, ensure_ascii=False)
        if "Yahaha Cover Agent" in payload_text:
            return FakeLLMAdapter().invoke(payload)
        if "toolResults" not in payload_text:
            output = {"type": "tool", "tool": {"name": "workspace.file_read", "args": {"path": "index.html", "maxBytes": 80000}}}
            text = json.dumps(output, ensure_ascii=False)
            raw = {"output_text": text, "usage": {"input_tokens": 9, "output_tokens": 7, "total_tokens": 16}}
            return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))
        previous_text = json.dumps(payload.get("input", [])[-1], ensure_ascii=False) if payload.get("input") else ""
        if "workspace.file_write" not in previous_text:
            output = {
                "type": "tool",
                "tool": {
                    "name": "workspace.file_write",
                    "args": {
                        "path": "index.html",
                        "content": """<!doctype html><html><body><canvas id='game'></canvas><script>const optimized=true; window.parent.postMessage({source:'yahaha-game',type:'game_ready',gameId:'opt'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
                    },
                },
            }
            text = json.dumps(output, ensure_ascii=False)
            raw = {"output_text": text, "usage": {"input_tokens": 10, "output_tokens": 20, "total_tokens": 30}}
            return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))
        assert "requestAnimationFrame" in payload_text
        output = {
            "type": "final",
            "output": {
                "Finished": True,
                "files": [
                    {
                        "path": "index.html",
                        "workspacePath": "index.html",
                    },
                    {"path": "manifest.json", "content": "{}"},
                    {"path": "source.json", "content": "{\"generator\":\"fake-opt-react\",\"optimized\":true}"},
                ],
                "cover": {"title": "Optimized LLM Arcade", "description": "Optimized by fake ReAct LLM.", "tags": ["llm", "optimized"]},
                "implementationSummary": "Read the previous index.html and produced an optimized version.",
                "safetyNotes": ["No privileged APIs."],
            },
        }
        text = json.dumps(output, ensure_ascii=False)
        raw = {"output_text": text, "usage": {"input_tokens": 12, "output_tokens": 38, "total_tokens": 50}}
        return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))


class BadLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        raw = {"output_text": "not json", "usage": {"output_tokens": 2}}
        return LLMGraphResult(text="not json", raw=raw, metrics=build_llm_call_metrics(payload, response_text="not json", response_raw=raw))


class BadCoverLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        payload_text = json.dumps(payload, ensure_ascii=False)
        if "Yahaha Cover Agent" in payload_text:
            raw = {"output_text": "{\"summary\":\"no image\"}", "usage": {"output_tokens": 3}}
            return LLMGraphResult(text=raw["output_text"], raw=raw, metrics=build_llm_call_metrics(payload, response_text=raw["output_text"], response_raw=raw))
        return FakeLLMAdapter().invoke(payload)


class UnsupportedImageLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        raw = {"ok": False, "error": {"message": "This model does not support image input."}}
        return LLMGraphResult(text="", raw=raw, metrics=build_llm_call_metrics(payload, response_text="", response_raw=raw))


def run() -> None:
    get_settings.cache_clear()
    assert get_settings().create_static_generation is False

    workspace_root = Path(__file__).resolve().parents[1]
    hydration_worktree = workspace_root / ".worktrees" / "hydrate-test"
    hydration_worktree.mkdir(parents=True, exist_ok=True)
    hydration_context = type(
        "HydrationContext",
        (),
        {
            "workspace": WorkspaceContext(
                run_id="hydrate-test",
                project_id="project-test",
                workspace_root=str(workspace_root),
                worktree_stub_path=str(hydration_worktree),
                branch_name=None,
                base_commit=None,
                cleanup_policy="manual",
                isolation_mode="stub",
                capability="read_write",
                status="prepared",
            )
        },
    )()
    WorkspaceFS(hydration_context.workspace).write_text(
        "index.html",
        "<!doctype html><html><body><canvas></canvas><script>requestAnimationFrame(()=>{});</script></body></html>",
    )
    hydrated = create_service._hydrate_output_from_workspace(
        {
            "type": "final",
            "output": {
                "Finished": True,
                "files": [{"path": "index.html", "workspacePath": "index.html", "content": "See workspace file: index.html"}],
            },
        },
        hydration_context,
    )
    hydrated_file = hydrated["output"]["files"][0]
    assert hydrated_file["content"].startswith("<!doctype html>")
    assert "See workspace file" not in hydrated_file["content"]

    placeholder_scan = create_service._scan_publish_artifacts(
        [AgentArtifact("index.html", b"See workspace file: index.html", "text/html; charset=utf-8", "bundle", "final")],
        "index.html",
    )
    assert placeholder_scan["passed"] is False
    assert any(issue["code"] == "ENTRY_WORKSPACE_PLACEHOLDER" for issue in placeholder_scan["issues"])

    create_service._make_graph_adapter = lambda ai_config: FakeLLMAdapter()  # type: ignore[assignment]

    client = TestClient(app)
    email = f"llm-{uuid4().hex[:10]}@yahaha.local"
    auth_register = client.post(
        "/auth/register",
        json={"email": email, "password": "password123", "displayName": "LLM User"},
    )
    assert auth_register.status_code == 200
    token = auth_register.json()["accessToken"]

    ai_config = client.put(
        "/create/ai-config",
        json={"baseUrl": "https://api.example.test/v1", "model": "test-model", "apiKey": "test-api-key"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert ai_config.status_code == 200

    create_job = client.post(
        "/create/jobs",
        json={"prompt": "make an llm arcade game", "files": [], "agentMode": "plan", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert create_job.status_code == 202
    payload = create_job.json()
    assert payload["status"] == "planning"
    final_job = client.get(f"/create/jobs/{payload['id']}", headers={"Authorization": f"Bearer {token}"})
    assert final_job.status_code == 200
    payload = final_job.json()
    assert payload["status"] == "completed"
    assert payload["agentMode"] == "plan"
    assert payload["gameSlug"].startswith("llm-arcade-")

    steps = client.get(f"/create/runs/{payload['runId']}/steps", headers={"Authorization": f"Bearer {token}"})
    assert steps.status_code == 200
    step_payload = steps.json()
    stages = [step["stage"] for step in step_payload]
    assert "llm_call" in stages
    assert "cover_prompt_rendered" in stages
    assert "cover_llm_call" in stages
    assert "cover_generated" in stages
    assert "cover_uploaded" in stages
    assert "llm_output_normalized" in stages
    assert "llm_generation_completed" in stages
    llm_step = next(step for step in step_payload if step["stage"] == "llm_call")
    assert llm_step["metrics"]["outputTokens"] == 34
    cover_step = next(step for step in step_payload if step["stage"] == "cover_generated")
    assert cover_step["metrics"]["contentType"] == "image/svg+xml"

    events = client.get(f"/create/runs/{payload['runId']}/events", headers={"Authorization": f"Bearer {token}"})
    assert events.status_code == 200
    assert "event: llm_call" in events.text
    assert "cover_uploaded" in events.text
    assert "event: done" in events.text

    games = client.get("/games")
    assert games.status_code == 200
    created_game = next(game for game in games.json() if game["id"] == payload["gameSlug"])
    assert created_game["coverUrl"].endswith(f"/games/{payload['gameSlug']}/cover")
    cover_response = client.get(f"/games/{payload['gameSlug']}/cover")
    assert cover_response.status_code == 200
    assert cover_response.headers["content-type"].startswith("image/svg+xml")

    manifest = client.get(f"/play/{payload['gameSlug']}/manifest")
    assert manifest.status_code == 200
    assert any(asset.endswith(f"/games/{payload['gameSlug']}/cover") for asset in manifest.json()["assets"])

    document = client.get(f"/play/{payload['gameSlug']}/document")
    assert document.status_code == 200
    assert "requestAnimationFrame" in document.text

    create_service._make_graph_adapter = lambda ai_config: OptReactLLMAdapter()  # type: ignore[assignment]
    opt_job = client.post(
        "/create/jobs",
        json={
            "prompt": "optimize this game with better movement",
            "files": [],
            "agentMode": "react",
            "createType": "opt",
            "projectId": payload["projectId"],
        },
        headers={"Authorization": f"Bearer {token}"},
    )
    assert opt_job.status_code == 202
    opt_start = opt_job.json()
    opt_final = client.get(f"/create/jobs/{opt_start['id']}", headers={"Authorization": f"Bearer {token}"})
    assert opt_final.status_code == 200
    opt_payload = opt_final.json()
    assert opt_payload["status"] == "completed"
    assert opt_payload["createType"] == "opt"
    assert opt_payload["agentMode"] == "react"
    assert opt_payload["projectId"] == payload["projectId"]
    opt_steps = client.get(f"/create/runs/{opt_payload['runId']}/steps", headers={"Authorization": f"Bearer {token}"})
    assert opt_steps.status_code == 200
    opt_step_payload = opt_steps.json()
    opt_stages = [step["stage"] for step in opt_step_payload]
    assert "refinement_context_loaded" in opt_stages
    tool_steps = [step for step in opt_step_payload if step["stage"] == "tool_call"]
    assert any(step["status"] == "succeeded" and step["metrics"]["toolName"] == "workspace.file_read" for step in tool_steps)
    assert any(step["status"] == "succeeded" and step["metrics"]["toolName"] == "workspace.file_write" for step in tool_steps)
    opt_document = client.get(f"/play/{opt_payload['gameSlug']}/document")
    assert opt_document.status_code == 200
    assert "optimized=true" in opt_document.text

    create_service._make_graph_adapter = lambda ai_config: BadLLMAdapter()  # type: ignore[assignment]
    failed_job = client.post(
        "/create/jobs",
        json={"prompt": "return malformed output", "files": [], "agentMode": "plan", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert failed_job.status_code == 202
    failed_start = failed_job.json()
    failed_final = client.get(f"/create/jobs/{failed_start['id']}", headers={"Authorization": f"Bearer {token}"})
    assert failed_final.status_code == 200
    failed_payload = failed_final.json()
    assert failed_payload["status"] == "failed"
    assert failed_payload["gameSlug"] is None
    failed_events = client.get(f"/create/runs/{failed_payload['runId']}/events", headers={"Authorization": f"Bearer {token}"})
    assert failed_events.status_code == 200
    assert "event: error" in failed_events.text

    create_service._make_graph_adapter = lambda ai_config: BadCoverLLMAdapter()  # type: ignore[assignment]
    failed_cover_job = client.post(
        "/create/jobs",
        json={"prompt": "valid game but invalid cover", "files": [], "agentMode": "plan", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert failed_cover_job.status_code == 202
    failed_cover_start = failed_cover_job.json()
    failed_cover_final = client.get(f"/create/jobs/{failed_cover_start['id']}", headers={"Authorization": f"Bearer {token}"})
    assert failed_cover_final.status_code == 200
    failed_cover_payload = failed_cover_final.json()
    assert failed_cover_payload["status"] == "failed"
    assert failed_cover_payload["gameSlug"] is None
    failed_cover_steps = client.get(f"/create/runs/{failed_cover_payload['runId']}/steps", headers={"Authorization": f"Bearer {token}"})
    assert failed_cover_steps.status_code == 200
    failed_cover_stages = [step["stage"] for step in failed_cover_steps.json()]
    assert "cover_llm_call" in failed_cover_stages
    assert "run_failed" in failed_cover_stages

    image_bytes = base64.b64decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=")
    upload = client.post(
        "/uploads",
        files={"file": ("sketch.png", image_bytes, "image/png")},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert upload.status_code == 200
    input_asset = upload.json()
    create_service._make_graph_adapter = lambda ai_config: UnsupportedImageLLMAdapter()  # type: ignore[assignment]
    unsupported_job = client.post(
        "/create/jobs",
        json={
            "prompt": "make a game from this image",
            "files": [],
            "inputAssets": [input_asset],
            "agentMode": "plan",
            "createType": "init",
        },
        headers={"Authorization": f"Bearer {token}"},
    )
    assert unsupported_job.status_code == 202
    unsupported_start = unsupported_job.json()
    unsupported_final = client.get(f"/create/jobs/{unsupported_start['id']}", headers={"Authorization": f"Bearer {token}"})
    assert unsupported_final.status_code == 200
    unsupported_payload = unsupported_final.json()
    assert unsupported_payload["status"] == "failed"
    assert unsupported_payload["gameSlug"] is None
    with create_service.db_connection() as connection:
        asset_row = connection.execute("SELECT id FROM assets WHERE id = %s", (input_asset["assetId"],)).fetchone()
        job_row = connection.execute("SELECT input_payload, error_code, error_message FROM generation_jobs WHERE id = %s", (unsupported_payload["id"],)).fetchone()
    assert asset_row is None
    assert job_row["input_payload"]["inputAssets"] == []
    assert job_row["error_code"] == "MULTIMODAL_UNSUPPORTED"
    assert "image input" in job_row["error_message"]


if __name__ == "__main__":
    run()
    print("create llm generation checks passed")
