from __future__ import annotations

import json
from typing import Any


FALLBACK_INDEX_HTML = """<!doctype html>
<html>
  <head><meta charset="utf-8"><title>Generated Game</title></head>
  <body>
    <canvas id="game"></canvas>
    <script>
      window.parent.postMessage({ source: "yahaha-game", type: "game_ready" }, "*");
    </script>
  </body>
</html>
"""


def fallback_main_agent_output(reason: str) -> dict[str, Any]:
    return {
        "files": [
            {"path": "index.html", "content": FALLBACK_INDEX_HTML},
            {
                "path": "manifest.json",
                "content": json.dumps(
                    {
                        "runtime": "iframe-srcdoc",
                        "entry": "index.html",
                        "communication": "postMessage",
                        "fallback": True,
                    },
                    ensure_ascii=False,
                    indent=2,
                ),
            },
            {
                "path": "source.json",
                "content": json.dumps(
                    {
                        "fallback": True,
                        "reason": reason,
                        "generator": "main-agent-output-parser",
                    },
                    ensure_ascii=False,
                    indent=2,
                ),
            },
        ],
        "cover": {
            "title": "Generated Game",
            "description": "Fallback output generated because the main agent response was not valid.",
            "tags": ["fallback"],
        },
        "implementationSummary": "Fallback JSON output was generated by backend constraints.",
        "safetyNotes": ["Fallback document avoids privileged browser APIs."],
        "fallback": True,
        "fallbackReason": reason,
    }


def _coerce_json(value: str | dict[str, Any]) -> tuple[dict[str, Any] | None, str | None]:
    if isinstance(value, dict):
        return value, None
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError as exc:
        return None, f"invalid_json: {exc.msg}"
    if not isinstance(parsed, dict):
        return None, "json_root_must_be_object"
    return parsed, None


def _valid_file_entry(entry: Any) -> bool:
    return isinstance(entry, dict) and isinstance(entry.get("path"), str) and isinstance(entry.get("content"), str)


def parse_main_agent_json_output(value: str | dict[str, Any]) -> dict[str, Any]:
    parsed, error = _coerce_json(value)
    if error or parsed is None:
        return fallback_main_agent_output(error or "invalid_output")

    files = parsed.get("files")
    if not isinstance(files, list) or not files or not all(_valid_file_entry(entry) for entry in files):
        return fallback_main_agent_output("files_must_be_non_empty_path_content_list")

    required_paths = {"index.html", "manifest.json", "source.json"}
    paths = {entry["path"] for entry in files}
    if not required_paths.issubset(paths):
        return fallback_main_agent_output("missing_required_files")

    cover = parsed.get("cover")
    if not isinstance(cover, dict):
        parsed["cover"] = {"title": "Generated Game", "description": "", "tags": []}
    parsed.setdefault("implementationSummary", "")
    parsed.setdefault("safetyNotes", [])
    parsed["fallback"] = False
    return parsed
