from pathlib import Path
import base64
import json
import os
import sys
from uuid import uuid4

from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
os.environ["CREATE_STATIC_GENERATION"] = "false"

from tests.support.integration import configure_test_environment, isolated_integration_test

configure_test_environment()

from app.config import get_settings
from app.agents.graphs.llm_adapter import LLMGraphResult, build_llm_call_metrics
from app.agents.create import AgentArtifact
from app.agents.create.cover_agent import build_cover_responses_payload
from app.agents.framework.workspace import WorkspaceContext, WorkspaceFS
from app.main import app
from app.services import create_service


class FakeLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        payload_text = json.dumps(payload, ensure_ascii=False)
        if "Gameweare Cover Agent" in payload_text:
            output = {
                "svg": "<svg xmlns='http://www.w3.org/2000/svg' width='1200' height='900'><rect width='1200' height='900' fill='#101827'/><text x='80' y='180' fill='#ffffff' font-size='88'>LLM Arcade</text></svg>",
                "mimeType": "image/svg+xml",
                "summary": "A generated SVG catalog cover for LLM Arcade.",
            }
            text = json.dumps(output, ensure_ascii=False)
            raw = {"output_text": text, "usage": {"input_tokens": 8, "output_tokens": 13, "total_tokens": 21}}
            return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))
        if "Gameweare ReAct Create Agent" in payload_text and "toolResults" not in payload_text:
            output = {
                "type": "tool",
                "tool": {
                    "name": "workspace.file_write",
                    "args": {
                        "path": "index.html",
                        "content": """<!doctype html><html><body><canvas id='game'></canvas><script>window.parent.postMessage({source:'gameweare-game',type:'game_ready',gameId:'x'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
                    },
                },
            }
            text = json.dumps(output, ensure_ascii=False)
            raw = {"output_text": text, "usage": {"input_tokens": 12, "output_tokens": 21, "total_tokens": 33}}
            return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))
        file_entry = (
            {"path": "index.html", "workspacePath": "index.html"}
            if "Gameweare ReAct Create Agent" in payload_text
            else {
                "path": "index.html",
                "content": """<!doctype html><html><body><canvas id='game'></canvas><script>window.parent.postMessage({source:'gameweare-game',type:'game_ready',gameId:'x'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
            }
        )
        output = {
            "type": "final",
            "output": {
                "Finished": True,
                "files": [file_entry],
                "cover": {"title": "LLM Arcade", "description": "Generated by fake LLM.", "tags": ["llm"]},
                "implementationSummary": "A minimal iframe-safe game document.",
                "safetyNotes": ["No privileged APIs."],
            },
        }
        text = json.dumps(output, ensure_ascii=False)
        raw = {"output_text": text, "usage": {"input_tokens": 12, "output_tokens": 34, "total_tokens": 46}}
        return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))


class OptReactLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        payload_text = json.dumps(payload, ensure_ascii=False)
        if "Gameweare Cover Agent" in payload_text:
            return FakeLLMAdapter().invoke(payload)
        if "toolResults" not in payload_text:
            output = {"type": "tool", "tool": {"name": "workspace.file_read", "args": {"path": "index.html", "maxBytes": 80000}}}
            text = json.dumps(output, ensure_ascii=False)
            raw = {"output_text": text, "usage": {"input_tokens": 9, "output_tokens": 7, "total_tokens": 16}}
            return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))
        previous_text = json.dumps(payload.get("input", [])[-1], ensure_ascii=False) if payload.get("input") else ""
        if "workspace.file_write" not in previous_text:
            output = {
                "type": "tool",
                "tool": {
                    "name": "workspace.file_write",
                    "args": {
                        "path": "index.html",
                        "content": """<!doctype html><html><body><canvas id='game'></canvas><script>const optimized=true; window.parent.postMessage({source:'gameweare-game',type:'game_ready',gameId:'opt'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
                    },
                },
            }
            text = json.dumps(output, ensure_ascii=False)
            raw = {"output_text": text, "usage": {"input_tokens": 10, "output_tokens": 20, "total_tokens": 30}}
            return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))
        assert "requestAnimationFrame" in payload_text
        output = {
            "type": "final",
            "output": {
                "Finished": True,
                "files": [
                    {
                        "path": "index.html",
                        "workspacePath": "index.html",
                    },
                    {"path": "manifest.json", "content": "{}"},
                    {"path": "source.json", "content": "{\"generator\":\"fake-opt-react\",\"optimized\":true}"},
                ],
                "cover": {"title": "Optimized LLM Arcade", "description": "Optimized by fake ReAct LLM.", "tags": ["llm", "optimized"]},
                "implementationSummary": "Read the previous index.html and produced an optimized version.",
                "safetyNotes": ["No privileged APIs."],
            },
        }
        text = json.dumps(output, ensure_ascii=False)
        raw = {"output_text": text, "usage": {"input_tokens": 12, "output_tokens": 38, "total_tokens": 50}}
        return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))


class RefineHTMLAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        payload_text = json.dumps(payload, ensure_ascii=False)
        if "Gameweare Cover Agent" in payload_text:
            return FakeLLMAdapter().invoke(payload)
        assert "Gameweare Refine Create Agent" in payload_text
        assert "requestAnimationFrame" in payload_text
        assert "Previous draft or published game artifacts" in payload_text
        output = {
            "type": "final",
            "output": {
                "Finished": True,
                "files": [
                    {
                        "path": "index.html",
                        "content": """<!doctype html><html><head><meta charset='utf-8'><title>Optimized LLM Arcade</title></head><body><canvas id='game'></canvas><script>const optimized=true; window.parent.postMessage({source:'gameweare-game',type:'game_ready',gameId:'opt'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
                    }
                ],
                "cover": {"title": "Optimized LLM Arcade", "description": "Optimized through refine JSON.", "tags": ["refined"]},
                "implementationSummary": "Refine returned the same JSON tool/final contract as other strategies.",
                "safetyNotes": ["No privileged APIs."],
            },
        }
        text = json.dumps(output, ensure_ascii=False)
        raw = {"output_text": text, "usage": {"input_tokens": 20, "output_tokens": 40, "total_tokens": 60}}
        return LLMGraphResult(text=text, raw=raw, metrics=build_llm_call_metrics(payload, response_text=text, response_raw=raw))


class BadLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        raw = {"output_text": "not json", "usage": {"output_tokens": 2}}
        return LLMGraphResult(text="not json", raw=raw, metrics=build_llm_call_metrics(payload, response_text="not json", response_raw=raw))


class BadCoverLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        payload_text = json.dumps(payload, ensure_ascii=False)
        if "Gameweare Cover Agent" in payload_text:
            raw = {"output_text": "{\"summary\":\"no image\"}", "usage": {"output_tokens": 3}}
            return LLMGraphResult(text=raw["output_text"], raw=raw, metrics=build_llm_call_metrics(payload, response_text=raw["output_text"], response_raw=raw))
        return FakeLLMAdapter().invoke(payload)


class UnsupportedImageLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        raw = {"ok": False, "error": {"message": "This model does not support image input."}}
        return LLMGraphResult(text="", raw=raw, metrics=build_llm_call_metrics(payload, response_text="", response_raw=raw))


class ProviderFailureLLMAdapter:
    def invoke(self, payload: dict) -> LLMGraphResult:
        raw = {"ok": False, "statusCode": 504, "error": {"code": "provider_timeout", "message": "upstream provider timed out"}}
        return LLMGraphResult(text="", raw=raw, metrics=build_llm_call_metrics(payload, response_text="", response_raw=raw))


def run() -> None:
    get_settings.cache_clear()
    assert get_settings().create_static_generation is False
    cover_prompt_payload = build_cover_responses_payload(
        model="test-model",
        user_request="make a game",
        game_title="Cover Contract",
        game_description="A game that needs a cover.",
    )
    cover_prompt_text = json.dumps(cover_prompt_payload, ensure_ascii=False)
    cover_user_contract = json.loads(cover_prompt_payload["input"][1]["content"][0]["text"])["outputContract"]
    assert "The response must include exactly one durable asset field: imageBase64 or svg" in cover_prompt_text
    assert "Never return only text, only summary" in cover_prompt_text
    assert cover_user_contract["requiredOneOf"] == ["imageBase64", "svg"]
    safe_scan = create_service._scan_publish_artifacts(
        [
            AgentArtifact(
                "index.html",
                b"<!doctype html><html><body><canvas></canvas><script>requestAnimationFrame(()=>{});</script></body></html>",
                "text/html",
                "bundle",
                "runtime",
            )
        ],
        "index.html",
    )
    assert safe_scan["passed"] is True
    allowed_parent_message_scan = create_service._scan_publish_artifacts(
        [
            AgentArtifact(
                "index.html",
                b"""<!doctype html><html><body><script>window . parent . postMessage({source:'gameweare-game',type:'game_ready',payload:{}}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
                "text/html",
                "bundle",
                "runtime",
            )
        ],
        "index.html",
    )
    assert allowed_parent_message_scan["passed"] is True
    for blocked_parent_html in (
        b"""<!doctype html><html><body><script>parent.postMessage({source:'gameweare-game',type:'game_ready'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
        b"""<!doctype html><html><body><script>const p = window.parent; requestAnimationFrame(()=>{});</script></body></html>""",
        b"""<!doctype html><html><body><script>window.parent.location.href = '/x'; requestAnimationFrame(()=>{});</script></body></html>""",
        b"""<!doctype html><html><body><script>window["parent"].postMessage({source:'gameweare-game'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
        b"""<!doctype html><html><body><script>parent["postMessage"]({source:'gameweare-game'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
        b"""<!doctype html><html><body><script>window?.parent.postMessage({source:'gameweare-game'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
        b"""<!doctype html><html><body><script>self.parent.postMessage({source:'gameweare-game'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
        b"""<!doctype html><html><body><script>globalThis.parent.postMessage({source:'gameweare-game'}, '*'); requestAnimationFrame(()=>{});</script></body></html>""",
    ):
        parent_scan = create_service._scan_publish_artifacts(
            [AgentArtifact("index.html", blocked_parent_html, "text/html", "bundle", "runtime")],
            "index.html",
        )
        parent_codes = {issue["code"] for issue in parent_scan["issues"]}
        assert parent_scan["passed"] is False
        assert "PARENT_ACCESS_BLOCKED" in parent_codes
    blocked_scan = create_service._scan_publish_artifacts(
        [
            AgentArtifact(
                "index.html",
                b"""<!doctype html><html><body onload='x()'><iframe src='https://evil.example'></iframe><a href='javascript:alert(1)'>x</a><script>fetch('/x'); localStorage.setItem('x','1');</script></body></html>""",
                "text/html",
                "bundle",
                "runtime",
            )
        ],
        "index.html",
    )
    blocked_codes = {issue["code"] for issue in blocked_scan["issues"]}
    assert blocked_scan["passed"] is False
    assert {"INLINE_EVENT_HANDLER_BLOCKED", "BLOCKED_HTML_TAG", "DANGEROUS_URL_BLOCKED", "NETWORK_FETCH_BLOCKED", "LOCAL_STORAGE_BLOCKED"} <= blocked_codes
    oversized_scan = create_service._scan_publish_artifacts(
        [AgentArtifact("index.html", b"<!doctype html><html><body><script></script>" + (b"x" * 1_500_001), "text/html", "bundle", "runtime")],
        "index.html",
    )
    assert any(issue["code"] == "ENTRY_SIZE_LIMIT" for issue in oversized_scan["issues"])

    workspace_root = Path(__file__).resolve().parents[1]
    hydration_worktree = workspace_root / ".worktrees" / "hydrate-test"
    hydration_worktree.mkdir(parents=True, exist_ok=True)
    hydration_context = type(
        "HydrationContext",
        (),
        {
            "workspace": WorkspaceContext(
                run_id="hydrate-test",
                project_id="project-test",
                workspace_root=str(workspace_root),
                worktree_stub_path=str(hydration_worktree),
                branch_name=None,
                base_commit=None,
                cleanup_policy="manual",
                isolation_mode="stub",
                capability="read_write",
                status="prepared",
            )
        },
    )()
    WorkspaceFS(hydration_context.workspace).write_text(
        "index.html",
        "<!doctype html><html><body><canvas></canvas><script>requestAnimationFrame(()=>{});</script></body></html>",
    )
    hydrated = create_service._hydrate_output_from_workspace(
        {
            "type": "final",
            "output": {
                "Finished": True,
                "files": [{"path": "index.html", "workspacePath": "index.html", "content": "See workspace file: index.html"}],
            },
        },
        hydration_context,
    )
    hydrated_file = hydrated["output"]["files"][0]
    assert hydrated_file["content"].startswith("<!doctype html>")
    assert "See workspace file" not in hydrated_file["content"]

    explicit_content = create_service._hydrate_output_from_workspace(
        {
            "type": "final",
            "output": {
                "Finished": True,
                "files": [{"path": "index.html", "content": "<!doctype html><html><body>new llm content</body></html>"}],
            },
        },
        hydration_context,
    )
    assert explicit_content["output"]["files"][0]["content"] == "<!doctype html><html><body>new llm content</body></html>"

    placeholder_scan = create_service._scan_publish_artifacts(
        [AgentArtifact("index.html", b"See workspace file: index.html", "text/html; charset=utf-8", "bundle", "final")],
        "index.html",
    )
    assert placeholder_scan["passed"] is False
    assert any(issue["code"] == "ENTRY_WORKSPACE_PLACEHOLDER" for issue in placeholder_scan["issues"])

    create_service._make_graph_adapter = lambda ai_config: FakeLLMAdapter()  # type: ignore[assignment]

    client = TestClient(app)
    email = f"llm-{uuid4().hex[:10]}@gameweare.local"
    auth_register = client.post(
        "/auth/register",
        json={"email": email, "password": "password123", "displayName": "LLM User"},
    )
    assert auth_register.status_code == 200
    token = auth_register.json()["accessToken"]

    ai_config = client.put(
        "/create/ai-config",
        json={"baseUrl": "https://api.example.test/v1", "model": "test-model", "apiKey": "test-api-key"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert ai_config.status_code == 200

    reject_job = client.post(
        "/create/jobs",
        json={"prompt": "make a plan that user rejects", "files": [], "agentMode": "plan", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert reject_job.status_code == 202
    reject_start = reject_job.json()
    reject_preview = client.get(f"/create/runs/{reject_start['runId']}/plan-preview", headers={"Authorization": f"Bearer {token}"})
    assert reject_preview.status_code == 200
    rejected = client.post(
        f"/create/runs/{reject_start['runId']}/plan-decision",
        json={"decision": "rejected"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert rejected.status_code == 200
    rejected_payload = rejected.json()
    assert rejected_payload["status"] == "canceled"
    assert rejected_payload["gameSlug"] is None
    rejected_steps = client.get(f"/create/runs/{reject_start['runId']}/steps", headers={"Authorization": f"Bearer {token}"})
    assert rejected_steps.status_code == 200
    rejected_stages = [step["stage"] for step in rejected_steps.json()]
    assert "plan_ready" in rejected_stages
    assert "plan_rejected" in rejected_stages

    create_job = client.post(
        "/create/jobs",
        json={"prompt": "make an llm arcade game", "files": [], "agentMode": "plan", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert create_job.status_code == 202
    payload = create_job.json()
    assert payload["status"] == "planning"
    preview = client.get(f"/create/runs/{payload['runId']}/plan-preview", headers={"Authorization": f"Bearer {token}"})
    assert preview.status_code == 200
    assert preview.json()["planPreview"]["plan"]
    accepted = client.post(
        f"/create/runs/{payload['runId']}/plan-decision",
        json={"decision": "accepted"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert accepted.status_code == 200
    payload = accepted.json()
    assert payload["status"] == "completed"
    assert payload["agentMode"] == "plan"
    assert payload["gameSlug"].startswith("llm-arcade-")

    steps = client.get(f"/create/runs/{payload['runId']}/steps", headers={"Authorization": f"Bearer {token}"})
    assert steps.status_code == 200
    step_payload = steps.json()
    stages = [step["stage"] for step in step_payload]
    assert "llm_call" in stages
    assert "cover_prompt_rendered" in stages
    assert "cover_llm_call" in stages
    assert "cover_generated" in stages
    assert "cover_uploaded" in stages
    assert "llm_output_normalized" in stages
    assert "llm_generation_completed" in stages
    assert "plan_ready" in stages
    assert "plan_accepted" in stages
    llm_step = next(step for step in step_payload if step["stage"] == "llm_call")
    assert llm_step["metrics"]["outputTokens"] == 34
    cover_step = next(step for step in step_payload if step["stage"] == "cover_generated")
    assert cover_step["metrics"]["contentType"] == "image/svg+xml"

    events = client.get(f"/create/runs/{payload['runId']}/events", headers={"Authorization": f"Bearer {token}"})
    assert events.status_code == 200
    assert "event: llm_call" in events.text
    assert "cover_uploaded" in events.text
    assert "event: done" in events.text

    draft_manifest = client.get(f"/play/{payload['gameSlug']}/manifest")
    assert draft_manifest.status_code == 404
    publish_response = client.post(f"/create/jobs/{payload['id']}/publish", headers={"Authorization": f"Bearer {token}"})
    assert publish_response.status_code == 200
    payload = publish_response.json()
    assert payload["publishStatus"] == "published"

    games = client.get("/games")
    assert games.status_code == 200
    created_game = next(game for game in games.json() if game["id"] == payload["gameSlug"])
    assert created_game["coverUrl"].endswith(f"/games/{payload['gameSlug']}/cover")
    cover_response = client.get(f"/games/{payload['gameSlug']}/cover")
    assert cover_response.status_code == 200
    assert cover_response.headers["content-type"].startswith("image/svg+xml")

    manifest = client.get(f"/play/{payload['gameSlug']}/manifest")
    assert manifest.status_code == 200
    assert manifest.json()["sandbox"] == ["allow-scripts"]
    assert "allow-same-origin" not in manifest.text
    assert any(asset.endswith(f"/games/{payload['gameSlug']}/cover") for asset in manifest.json()["assets"])

    document = client.get(f"/play/{payload['gameSlug']}/document")
    assert document.status_code == 200
    assert "requestAnimationFrame" in document.text

    preview = client.get(f"/create/projects/{payload['projectId']}/preview", headers={"Authorization": f"Bearer {token}"})
    assert preview.status_code == 200
    assert preview.json()["versionNo"] == 1
    assert "requestAnimationFrame" in preview.json()["html"]

    create_service._make_graph_adapter = lambda ai_config: RefineHTMLAdapter()  # type: ignore[assignment]
    opt_job = client.post(
        "/create/jobs",
        json={
            "prompt": "optimize this game with better movement",
            "files": [],
            "agentMode": "refine",
            "createType": "opt",
            "projectId": payload["projectId"],
        },
        headers={"Authorization": f"Bearer {token}"},
    )
    assert opt_job.status_code == 202
    opt_start = opt_job.json()
    opt_final = client.get(f"/create/jobs/{opt_start['id']}", headers={"Authorization": f"Bearer {token}"})
    assert opt_final.status_code == 200
    opt_payload = opt_final.json()
    assert opt_payload["status"] == "completed"
    assert opt_payload["createType"] == "opt"
    assert opt_payload["agentMode"] == "refine"
    assert opt_payload["projectId"] == payload["projectId"]
    opt_steps = client.get(f"/create/runs/{opt_payload['runId']}/steps", headers={"Authorization": f"Bearer {token}"})
    assert opt_steps.status_code == 200
    opt_step_payload = opt_steps.json()
    opt_stages = [step["stage"] for step in opt_step_payload]
    assert "refinement_context_loaded" in opt_stages
    assert "llm_output_normalized" in opt_stages
    assert opt_payload["publishStatus"] == "draft"
    opt_publish = client.post(f"/create/jobs/{opt_payload['id']}/publish", headers={"Authorization": f"Bearer {token}"})
    assert opt_publish.status_code == 200
    opt_payload = opt_publish.json()
    opt_versions = client.get(f"/games/{opt_payload['gameSlug']}/versions", headers={"Authorization": f"Bearer {token}"})
    assert opt_versions.status_code == 200
    assert opt_versions.json()[0]["versionNo"] == 2
    assert opt_versions.json()[0]["current"] is True
    opt_document = client.get(f"/play/{opt_payload['gameSlug']}/document")
    assert opt_document.status_code == 200
    assert "optimized=true" in opt_document.text

    create_service._make_graph_adapter = lambda ai_config: BadLLMAdapter()  # type: ignore[assignment]
    failed_job = client.post(
        "/create/jobs",
        json={"prompt": "return malformed output", "files": [], "agentMode": "react", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert failed_job.status_code == 202
    failed_start = failed_job.json()
    failed_final = client.get(f"/create/jobs/{failed_start['id']}", headers={"Authorization": f"Bearer {token}"})
    assert failed_final.status_code == 200
    failed_payload = failed_final.json()
    assert failed_payload["status"] == "failed"
    assert failed_payload["gameSlug"] is None
    failed_events = client.get(f"/create/runs/{failed_payload['runId']}/events", headers={"Authorization": f"Bearer {token}"})
    assert failed_events.status_code == 200
    assert "event: error" in failed_events.text

    create_service._make_graph_adapter = lambda ai_config: ProviderFailureLLMAdapter()  # type: ignore[assignment]
    provider_failed_job = client.post(
        "/create/jobs",
        json={"prompt": "provider should fail with diagnostics", "files": [], "agentMode": "react", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert provider_failed_job.status_code == 202
    provider_failed_start = provider_failed_job.json()
    provider_failed_final = client.get(f"/create/jobs/{provider_failed_start['id']}", headers={"Authorization": f"Bearer {token}"})
    assert provider_failed_final.status_code == 200
    provider_failed_payload = provider_failed_final.json()
    assert provider_failed_payload["status"] == "failed"
    provider_failed_steps = client.get(f"/create/runs/{provider_failed_payload['runId']}/steps", headers={"Authorization": f"Bearer {token}"})
    assert provider_failed_steps.status_code == 200
    provider_steps = provider_failed_steps.json()
    provider_llm_step = next(step for step in provider_steps if step["stage"] == "llm_call")
    assert provider_llm_step["status"] == "failed"
    assert provider_llm_step["metrics"]["providerError"]["code"] == "provider_timeout"
    assert any(step["stage"] == "llm_generation_failed" and step["metrics"]["providerError"]["statusCode"] == 504 for step in provider_steps)
    assert any(step["stage"] == "run_failed" and step["metrics"]["providerError"]["code"] == "provider_timeout" for step in provider_steps)
    from app.services.maintenance_service import list_failed_create_runs

    maintainer_run = next(run for run in list_failed_create_runs(limit=20) if run.runId == provider_failed_payload["runId"])
    maintainer_llm_step = next(step for step in maintainer_run.steps if step.stage == "llm_call")
    assert maintainer_llm_step.metrics["providerError"]["code"] == "provider_timeout"

    create_service._make_graph_adapter = lambda ai_config: BadCoverLLMAdapter()  # type: ignore[assignment]
    degraded_cover_job = client.post(
        "/create/jobs",
        json={"prompt": "valid game but invalid cover", "files": [], "agentMode": "plan", "createType": "init"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert degraded_cover_job.status_code == 202
    degraded_cover_start = degraded_cover_job.json()
    degraded_cover_accept = client.post(
        f"/create/runs/{degraded_cover_start['runId']}/plan-decision",
        json={"decision": "accepted"},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert degraded_cover_accept.status_code == 200
    degraded_cover_payload = degraded_cover_accept.json()
    assert degraded_cover_payload["status"] == "completed"
    assert degraded_cover_payload["gameSlug"]
    degraded_cover_steps = client.get(f"/create/runs/{degraded_cover_payload['runId']}/steps", headers={"Authorization": f"Bearer {token}"})
    assert degraded_cover_steps.status_code == 200
    degraded_cover_step_payload = degraded_cover_steps.json()
    degraded_cover_stages = [step["stage"] for step in degraded_cover_step_payload]
    assert "cover_llm_call" in degraded_cover_stages
    assert "cover_generation_degraded" in degraded_cover_stages
    assert "cover_uploaded" in degraded_cover_stages
    assert "run_failed" not in degraded_cover_stages
    degraded_step = next(step for step in degraded_cover_step_payload if step["stage"] == "cover_generation_degraded")
    assert degraded_step["metrics"]["reason"] == "cover_output_contract_failed"
    completed_step = next(step for step in degraded_cover_step_payload if step["stage"] == "run_completed")
    assert completed_step["metrics"]["coverUrl"]

    image_bytes = base64.b64decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=")
    upload = client.post(
        "/uploads",
        files={"file": ("sketch.png", image_bytes, "image/png")},
        headers={"Authorization": f"Bearer {token}"},
    )
    assert upload.status_code == 200
    input_asset = upload.json()
    create_service._make_graph_adapter = lambda ai_config: UnsupportedImageLLMAdapter()  # type: ignore[assignment]
    unsupported_job = client.post(
        "/create/jobs",
        json={
            "prompt": "make a game from this image",
            "files": [],
            "inputAssets": [input_asset],
            "agentMode": "plan",
            "createType": "init",
        },
        headers={"Authorization": f"Bearer {token}"},
    )
    assert unsupported_job.status_code == 202
    unsupported_start = unsupported_job.json()
    unsupported_final = client.get(f"/create/jobs/{unsupported_start['id']}", headers={"Authorization": f"Bearer {token}"})
    assert unsupported_final.status_code == 200
    unsupported_payload = unsupported_final.json()
    assert unsupported_payload["status"] == "failed"
    assert unsupported_payload["gameSlug"] is None
    with create_service.db_connection() as connection:
        asset_row = connection.execute("SELECT id FROM assets WHERE id = %s", (input_asset["assetId"],)).fetchone()
        job_row = connection.execute("SELECT input_payload, error_code, error_message FROM generation_jobs WHERE id = %s", (unsupported_payload["id"],)).fetchone()
    assert asset_row is None
    assert job_row["input_payload"]["inputAssets"] == []
    assert job_row["error_code"] == "MULTIMODAL_UNSUPPORTED"
    assert "image input" in job_row["error_message"]


if __name__ == "__main__":
    with isolated_integration_test():
        run()
    print("create llm generation checks passed")
